### ISSUE TITLE
expose ldap email as "PS1User.email" property

### ISSUE THREAD

**Issue by dkoppel** [hef/ps1auth#109]
In attempting to incorporate SSO features for discourse, I need to associate accounts by email and assert this information to another application from the PS1User object.  Unfortunately we are not exporting email to LDAP, it appears.

In [90]: PS1User.objects.all()[0].ldap_user
Out[90]: {'uSNCreated': ['3774'], 'lastLogon': ['0'], 'accountExpires': ['9223372036854775807'], 'userAccountControl': ['512'], 'objectClass': ['top', 'person', 'organizationalPerson', 'user'], 'sAMAccountType': ['805306368'], 'countryCode': ['0'], 'instanceType': ['4'], 'whenCreated': ['20150713001442.0Z'], 'userPrincipalName': ['hacker@VAGRANT'], 'primaryGroupID': ['513'], 'lastLogoff': ['0'], 'name': ['hacker'], 'sAMAccountName': ['hacker'], 'objectSid': [b'\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\x07\x7f`+\xbc\xf6\xd4\xc8\xb7\xee\xc6^P\x04\x00\x00'], 'objectGUID': [b'r\xb8V\xb2\x0b\xe3\x8e@\xbf\x9dzc\xcb\x94\xdd\x9d'], 'uSNChanged': ['3777'], 'codePage': ['0'], 'cn': ['hacker'], 'pwdLastSet': ['130812200820000000'], 'objectCategory': ['CN=Person,CN=Schema,CN=Configuration,DC=vagrant,DC=lan'], 'memberOf': ['CN=Domain Admins,CN=Users,DC=vagrant,DC=lan'], 'logonCount': ['0'], 'badPwdCount': ['0'], 'distinguishedName': ['CN=hacker,CN=Users,DC=vagrant,DC=lan'], 'whenChanged': ['20150713001442.0Z'], 'badPasswordTime': ['0']}

ldapsearch -x -H ldap://localhost -b 'CN=Users,DC=vagrant,DC=lan' -D "VAGRANT\kuroishi" -W

dn: CN=hacker,CN=Users,DC=vagrant,DC=lan
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: hacker
instanceType: 4
whenCreated: 20150713001442.0Z
whenChanged: 20150713001442.0Z
uSNCreated: 3774
name: hacker
objectGUID:: crhWsgvjjkC/nXpjy5TdnQ==
badPwdCount: 0
codePage: 0
countryCode: 0
badPasswordTime: 0
lastLogoff: 0
lastLogon: 0
primaryGroupID: 513
objectSid:: AQUAAAAAAAUVAAAAB39gK7z21Mi37sZeUAQAAA==
accountExpires: 9223372036854775807
logonCount: 0
sAMAccountName: hacker
sAMAccountType: 805306368
userPrincipalName: hacker@VAGRANT
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=vagrant,DC=lan
userAccountControl: 512
memberOf: CN=Domain Admins,CN=Users,DC=vagrant,DC=lan
pwdLastSet: 130812200820000000
uSNChanged: 3777
distinguishedName: CN=hacker,CN=Users,DC=vagrant,DC=lan

Ideally we can add this as a class method for PS1User objects as well, so we can just call <PS1User: hacker>.get_email or similar.

**Comment by hef** [comment]
The 'mail'  attribute as filled out as part of the signup process, and not part of the MM process.

https://github.com/hef/ps1auth/blob/develop/signup/forms.py#L105
https://github.com/hef/ps1auth/blob/develop/accounts/models.py#L31-L32

I checked the prod database, and the mail attribute is present on most user accounts.

the management command <code>./manage create_person -m foo@example.com foo</code> should simulate adding a user and attaching an email to the user account.

The create_person command skips a lot of checks that the signup form requires, so email and last names are required via the form, but not required for management commands.


Feel free to reopen if I got something wrong or similar.

**Comment by hef** [comment]
reopeneing as "expose email" as a property on PS1User
