### ISSUE TITLE
Allow members to view a list of their member points

### ISSUE THREAD

**Issue by codersquid** [hef/ps1auth#131]
We should have a user profile page and included in that functionality, we should have a place where people can see their points and the dates for when they were awarded so that they'll know when the points expire.

**Comment by buildmon** [comment]
The second part of that exists:
https://members.pumpingstationone.org/memberpoints/my_points/

**Comment by codersquid** [comment]
I didn't remember that. For the profile thing, I expect #117 and #78 to cause it to exist.
