### ISSUE TITLE
authorization tracking

### ISSUE THREAD

**Issue by loansindi** [hef/ps1auth#43]
The lists on the wiki aren't great and managing domain groups isn't very fun. 

* allow web management of users and groups. Let an area host or authorizor log into the members site to add someone to the laser or shopbot domain groups with an easy button press
* allow users to list their authorizations on their profile and automatically build a list of authorized users for our tools (tie it into the wiki somehow?)

**Comment by hef** [comment]
next release will have manageable group permissions.
