### ISSUE TITLE
Member can't see menu after logging in

### ISSUE THREAD

**Issue by justintconroy** [hef/ps1auth#58]
We had a new member last night who was trying to set up RFID for himself, but after he logged on to the member site, the menu at the top of the screen wasn't visible. Instead, there was a button that said "Sign In" which took you back to the login page.

**Comment by justintconroy** [comment]
I just had another regular member log in and he also had the same problem. I think maybe the menu is only being shown to domain admins and other people who can do member management (maybe?).

**Comment by hef** [comment]
a2e324e8edce832481e1ed245363ef4464c3151c broke this
