### ISSUE TITLE
Arbitrary users with the correct URL can grant other members (or themselves) member points

### ISSUE THREAD

**Issue by justintconroy** [hef/ps1auth#66]
As the title says. There's nothing preventing an ordinary user from accessing the "grant" page (also the "consume" and "list" pages) for any user as long as they have the object_guid of a user and adding member points to them. These pages, and especially the actions to add/subtract points should be restricted to authorized users, i.e. admins and/or board members.

I noticed that the member points no longer keep track of which user added them, so it wouldn't even be possible to see after the fact if someone gave themselves a member point.

**Comment by eastein** [comment]
Ruh roh

**Comment by justintconroy** [comment]
Oh, I was sort of wrong. You don't even need to be logged in to access the grant and consume pages, but trying to grant or consume a point when  you're not logged in gives you a big ugly exception, so at least not-logged-in randoms from the internet won't be able to steal our member points.
