### ISSUE TITLE
User fields in member management show GUID instead of username.

### ISSUE THREAD

**Issue by justintconroy** [hef/ps1auth#70]
Various fields on the member management pages show a GUID instead of a username. 
See below:
![userfield](https://cloud.githubusercontent.com/assets/214411/6701094/ddc1d97a-cce5-11e4-9d14-9da817ff779c.PNG)

and:

![idcheckedby](https://cloud.githubusercontent.com/assets/214411/6701096/e023c9ee-cce5-11e4-9a48-998545b90120.PNG)

Seems fairly user unfriendly.

**Comment by justintconroy** [comment]
The second example came from testing the python3 pull request and will probably be fixed by changing the `__unicode__()` methods defined in classes to `__str__()`. The first example is live in production, so it probably will not be fixed by that.

**Comment by hef** [comment]
this should get fixed by 736447cc7d7bf23357b43f25c2f358b8ab473952

**Comment by justintconroy** [comment]
It did indeed look fixed in the Python3 pull request. Since that's merged into develop now, I think this can be closed.
