### ISSUE TITLE
Samba fails to start on vagrant up

### ISSUE THREAD

**Issue by dkoppel** [hef/ps1auth#81]
This is probably some of the breakage due to the old base image that Hef has mentioned.

Apr 29 02:55:22 archlinux.vagrant.vm samba[4919]: /usr/bin/samba: error while loading shared libraries: libgnutls.so.30: cannot open shared object file: No such file or directory
Apr 29 02:55:22 archlinux.vagrant.vm systemd[1]: samba.service: control process exited, code=exited status=127
Apr 29 02:55:22 archlinux.vagrant.vm systemd[1]: Failed to start Samba AD Daemon.

**Comment by dkoppel** [comment]
After installing current gnutls and nettle from pacman I get: 

Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: [2015/04/29 03:01:18.320234,  0] ../source4/smbd/server.c:475(binary_smbd_main)
Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: At this time the 'samba' binary should only be used for either:
Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: 'server role = active directory domain controller' or to access the ntvfs file server with 'server services = +smb' or the rpc proxy with '
Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: You should start smbd/nmbd/winbindd instead for domain member and standalone file server tasks
Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: [2015/04/29 03:01:18.320376,  0] ../lib/util/become_daemon.c:111(exit_daemon)
Apr 29 03:01:18 archlinux.vagrant.vm samba[5042]: STATUS=daemon failed to start: Samba detected misconfigured 'server role' and exited. Check logs for details, error code 22
Apr 29 03:01:18 archlinux.vagrant.vm systemd[1]: samba.service: main process exited, code=exited, status=1/FAILURE
Apr 29 03:01:18 archlinux.vagrant.vm systemd[1]: Unit samba.service entered failed state.
Apr 29 03:01:18 archlinux.vagrant.vm systemd[1]: samba.service failed.

This is less fun.

**Comment by dkoppel** [comment]
working after a pacman -Syu and re-running the samba-tool provisioning.  Not sure I want to add a pacman -Syu to the Vagrantfile though.

**Comment by loansindi** [comment]
Arch offers a netboot that lives at a static URL - could the vagrant file point at that (i'm just spitballing here)?

**Comment by hef** [comment]
c7d1f279869b16f0c68f8b4213c04f59ebc6d8f5 should fix this.  It's currently in PR #79

**Comment by dkoppel** [comment]
confirmed, that fixes the issue, will test ldap_group now so we can merge back to develop.
