### ISSUE TITLE
Would it be useful to have a count of pending members?

### ISSUE THREAD

**Issue by codersquid** [hef/ps1auth#92]
Pending members are people who haven't had IDs checked. And we could have a filter to show only pending members so we can see the backlog and maybe get in touch with people to see what's up.

also, are they counted in quorum or in some weird voting limbo? (haven't had a  chance to read the src to check yet, sorry. this will serve as a reminder for me).

**Comment by loansindi** [comment]
I think we'd need a 'pending' status for folks who have paid but not gotten IDs checked, but this seems like a good plan. I'm not super enamored with the way things work right now.

**Comment by hef** [comment]
closing, as I don't think @codersquid is pursuing this anymore.
