### ISSUE TITLE
Full Member Voting - Allow members to opt out of voting

### ISSUE THREAD

**Issue by amishHammer** [hef/ps1auth#95]
Add a flag in the members site that allows a full member to opt out of voting if they only have full membership for storage.  This flag should be used when calculating quorum.

**Comment by loansindi** [comment]
This would have to work in conjunction with a full fledged voting module or
else there would be implications of opted-out members voting in person.

**Comment by amishHammer** [comment]
Thats a good point, but I think it carries the same risks as a starving hacker voting in person at a meeting.  We currently don't check that people who put their hands up are full members.

**Comment by loansindi** [comment]
Intentionally implementing a broken feature for a process that's already
broken doesn't seem like a good use of time.

**Comment by KoalaBro2** [comment]
If a member opts out of voting, then votes at a meeting, then in my opinion, he has chosen to momentarily opt back in, and then immediately opt back out again after the vote.  I don't see that as a violation of our policies in any way.  The only potential issue is that his opting back in momentarily would theoretically raise our quorum requirement by 1/3rd of a person.

Also, I would suggest that the default should be opted out, and people should have to affirmatively opt into voting.  Generally speaking, the people who are not interested in voting are likely to be less engaged in the running of the organization, and are less likely to take proactive steps to remove themselves from the voting rolls.

**Comment by justintconroy** [comment]
The momentary opt-in is actually part of the bylaws already. :-)

https://wiki.pumpingstationone.org/Bylaws#Non-Voting_Members

"As a convenience, Non-Voting Members *can* opt-in to voting for any issue without revoking their Non-Voting status. They will count toward quorum for any vote in which they participate."
