### ISSUE TITLE
update LDAP requirements

### ISSUE THREAD

**Issue by dkoppel** [hef/ps1auth#96]
When provisioning a fresh vagrant instance, the specific version of the LDAP3 requirement is unavailable.

I will attempt testing with 0.9.8.4
 
==> default: Collecting ldap3==0.9.7.2 (from -r /vagrant/requirements/base.txt (line 2))
==> default:   Could not find a version that satisfies the requirement ldap3==0.9.7.2 (from -r /vagrant/requirements/base.txt (line 2)) (from versions: 0.9.8.2.post1, 0.9.8.3, 0.9.8.3.post1, 0.9.8.4)
==> default:   No distributions matching the version for ldap3==0.9.7.2 (from -r /vagrant/requirements/base.txt (line 2))

**Comment by hef** [comment]
Fixed by dkoppel
